import os
"""
Django settings for safebill project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Initialise environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--pd+&8025(uqd_97*s)=p1a+vp82y%1%zh)sp5y(p0a@66j38l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)


def _env_list(var_name, default_list):
    value = os.environ.get(var_name)
    if not value:
        return default_list
    # Support comma-separated values with optional spaces
    return [item.strip() for item in value.split(",") if item.strip()]

ALLOWED_HOSTS = _env_list(
    "ALLOWED_HOSTS",
    [
        "https://safebill.fr",
        "http://safebill.fr",
        "api.safebill.fr",
        "https://www.safebill.fr",
        "http://localhost:3000",  # For development
        "http://127.0.0.1:3000", # For development
        "https://dea6eb7b074c.ngrok-free.app",
        "dea6eb7b074c.ngrok-free.app",
    ],
)


# to allow all credentials (cookies, authorization headers, etc.) to be included in cross-origin requests
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    [
        "https://safebill.fr",
        "http://safebill.fr",
        "api.safebill.fr",
        "https://www.safebill.fr",
        "http://localhost:3000",  # For development
        "http://127.0.0.1:3000", # For development
    ],
)

# CSRF settings
CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    [
        "https://safebill.fr",
        "https://api.safebill.fr",

    ],
)

# For production, disable this
#CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)

# Allow custom headers for language detection and GDPR consent
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-user-language',  # Custom header for language detection
    'x-consent-status',  # GDPR consent status header
]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party-apps
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "accounts",
    "bussiness_documents",
    "projects",
    "notifications",
    "feedback",
    "disputes",
    # Chat
    "chat",
    "adminpanelApp",
    "connect_stripe",
    "payments",
    "hubspot",
    "subscription",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "utils.consent_middleware.ConsentMiddleware",  # GDPR consent checking
    "utils.language_middleware.LanguageMiddleware",  # Custom language middleware
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Disabled for PDF iframe
]

ROOT_URLCONF = "safebill.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ASGI/WSGI
WSGI_APPLICATION = "safebill.wsgi.application"
ASGI_APPLICATION = "safebill.asgi.application"

# Django Channels Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [env('REDIS_URL', default='redis://127.0.0.1:6379/1')],
        },
    },
}

# Note: MIDDLEWARE is already defined above, no need to redefine

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('fr', 'Français'),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Site URL for email templates
SITE_URL = env('SITE_URL', default='https://safebill.fr')
SITE_LOGO_URL = env('SITE_LOGO_URL', default='https://safebill.fr/static/images/Safe_Bill_Logo_Bleu.png')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# Simple JWT settings (customize as needed)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Update Django's User.last_login on successful token obtain/refresh
    "UPDATE_LAST_LOGIN": True,
}

# Note: CHANNEL_LAYERS is already defined above with Redis configuration

# Email backend - Hostinger Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# Hostinger SMTP settings for safebill.fr domain
# SMTP Server: smtp.hostinger.com
EMAIL_HOST = env("EMAIL_HOST", default="smtp.hostinger.com")
EMAIL_PORT = int(env("EMAIL_PORT", default=587))
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
# Connection timeout and retry settings
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=60)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER or "contact@safebill.fr")
# Server email (for error messages)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Additional email settings for better deliverability
EMAIL_USE_LOCALTIME = False
FRONTEND_URL = env("FRONTEND_URL")
SIRET_VALIDATION_ACCESS_TOKEN = env("SIRET_VALIDATION_ACCESS_TOKEN")
STRIPE_API_KEY = env("STRIPE_API_KEY")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_CONNECT_WEBHOOK_SECRET = env("STRIPE_CONNECT_WEBHOOK_SECRET")
STRIPE_VERIFICATION_FLOW_ID = env("STRIPE_VERIFICATION_FLOW_ID")
STRIPE_SUBSCRIPTION_WEBHOOK_SECRET = env("STRIPE_SUBSCRIPTION_WEBHOOK_SECRET", default="")
STRIPE_SUBSCRIPTION_PRICE_ID = env("STRIPE_SUBSCRIPTION_PRICE_ID", default="")

# X-Frame-Options disabled for PDF iframe embedding

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'projects': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'disputes': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'hubspot': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=env('REDIS_URL', default='redis://127.0.0.1:6379/0'))
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=env('REDIS_URL', default='redis://127.0.0.1:6379/0'))
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_DEFAULT_QUEUE = 'emails'

# Celery Beat Configuration
CELERY_BEAT_SCHEDULE = {
    'process-hubspot-sync-queue': {
        'task': 'hubspot.tasks.process_sync_queue',
        'schedule': float(os.environ.get('HUBSPOT_PROCESS_SYNC_QUEUE_INTERVAL', 7200.0)),
        'options': {
            'queue': 'emails',
            'priority': 5,
        }
    },
    'retry-failed-hubspot-syncs': {
        'task': 'hubspot.tasks.retry_failed_sync_items',
        'schedule': float(os.environ.get('HUBSPOT_RETRY_FAILED_SYNC_INTERVAL', 3600.0)),
        'options': {
            'queue': 'emails',
            'priority': 3,
        }
    },
    'cleanup-hubspot-sync-queue': {
        'task': 'hubspot.tasks.cleanup_old_sync_queue_items',
        'schedule': float(os.environ.get('HUBSPOT_CLEANUP_SYNC_QUEUE_INTERVAL', 86400.0)),
        'options': {
            'queue': 'emails',
            'priority': 1,
        }
    },
    'no-project-nurture-orchestrator': {
        'task': 'feedback.tasks.orchestrate_no_project_nurture_task',
        'schedule': float(os.environ['NO_PROJECT_ORCHESTRATOR_INTERVAL']),
        'options': {
            'queue': 'emails',
            'priority': 4,
        }
    },
    'relogin-reminder-orchestrator': {
        'task': 'accounts.tasks.orchestrate_relogin_reminder_task',
        'schedule': float(os.environ['RELOGIN_ORCHESTRATOR_INTERVAL']),
        'options': {
            'queue': 'emails',
            'priority': 4,
        }
    },
    'success-story-orchestrator': {
        'task': 'accounts.tasks.orchestrate_success_story_emails_task',
        'schedule': float(os.environ['SUCCESS_STORY_ORCHESTRATOR_INTERVAL']),
        'options': {
            'queue': 'emails',
            'priority': 4,
        }
    },
    'cleanup-old-email-logs': {
        'task': 'feedback.tasks.cleanup_old_email_logs_task',
        'schedule': float(os.environ.get('EMAIL_LOG_CLEANUP_INTERVAL', '86400.0')),  # Default: daily (24 hours)
        'options': {
            'queue': 'emails',
            'priority': 1,
        }
    },
}

# Celery Beat max loop interval
CELERY_BEAT_MAX_LOOP_INTERVAL = int(os.environ.get('CELERY_BEAT_MAX_LOOP_INTERVAL', 3600))

# Celery Task Routing
CELERY_TASK_ROUTES = {
    'projects.tasks.*': {'queue': 'emails'},
    'disputes.tasks.*': {'queue': 'emails'},
    'hubspot.tasks.*': {'queue': 'emails'},
    'accounts.tasks.*': {'queue': 'emails'},
    'payments.tasks.*': {'queue': 'emails'},
    'feedback.tasks.*': {'queue': 'emails'},
}

# Celery Task Discovery
CELERY_IMPORTS = [
    'projects.tasks',
    'disputes.tasks',
    'hubspot.tasks',
    'accounts.tasks',
    'payments.tasks',
    'feedback.tasks',
]

# HubSpot Integration
# Private App token for direct API access
HUBSPOT_PRIVATE_APP_TOKEN = env("HUBSPOT_PRIVATE_APP_TOKEN", default="")
# Base URL for HubSpot APIs (overrideable for testing/mocking)
HUBSPOT_API_BASE = env("HUBSPOT_API_BASE", default="https://api.hubapi.com")
# Tickets pipeline to use for disputes (string ID shown in HubSpot UI, often "0")
HUBSPOT_TICKETS_PIPELINE = env("HUBSPOT_TICKETS_PIPELINE", default="0")
HUBSPOT_MILESTONE_OBJECT = env("HUBSPOT_MILESTONE_OBJECT")
HUBSPOT_REVENUE_OBJECT = env("HUBSPOT_REVENUE_OBJECT")
HUBSPOT_FEEDBACK_OBJECT = env("HUBSPOT_FEEDBACK_OBJECT")
HUBSPOT_CONTACT_MESSAGE_OBJECT = env("HUBSPOT_CONTACT_MESSAGE_OBJECT")
HUBSPOT_PAYMENTS_OBJECT = env("HUBSPOT_PAYMENTS_OBJECT")
# Custom Lead object (used for CallbackRequest → Lead)
HUBSPOT_LEAD_OBJECT = env("HUBSPOT_LEAD_OBJECT", default="leads")
# Lead association type overrides (optional)
HUBSPOT_LEAD_TO_PRIMARY_CONTACT_TYPE_ID = env("HUBSPOT_LEAD_TO_PRIMARY_CONTACT_TYPE_ID", default=None)
HUBSPOT_LEAD_TO_PRIMARY_COMPANY_TYPE_ID = env("HUBSPOT_LEAD_TO_PRIMARY_COMPANY_TYPE_ID", default=None)
# Core HubSpot settings
HUBSPOT_SYNC_ENABLED = env.bool('HUBSPOT_SYNC_ENABLED')
HUBSPOT_SYNC_DEBUG = env.bool('HUBSPOT_SYNC_DEBUG')
HUBSPOT_SYNC_TIMEOUT = env.int('HUBSPOT_SYNC_TIMEOUT')

# Feature flags for safe deployment
HUBSPOT_USER_SIGNALS_ENABLED = env.bool('HUBSPOT_USER_SIGNALS_ENABLED', default=True)
HUBSPOT_COMPANY_SIGNALS_ENABLED = env.bool('HUBSPOT_COMPANY_SIGNALS_ENABLED', default=True)
HUBSPOT_PROJECT_SIGNALS_ENABLED = env.bool('HUBSPOT_PROJECT_SIGNALS_ENABLED', default=True)
HUBSPOT_MILESTONE_SIGNALS_ENABLED = env.bool('HUBSPOT_MILESTONE_SIGNALS_ENABLED', default=True)
HUBSPOT_SIGNALS_DEBUG = env.bool('HUBSPOT_SIGNALS_DEBUG', default=False)

# Rate limiting and circuit breaker
HUBSPOT_RATE_LIMIT_MAX = env.int('HUBSPOT_RATE_LIMIT_MAX')
HUBSPOT_RATE_LIMIT_WINDOW = env.int('HUBSPOT_RATE_LIMIT_WINDOW')
HUBSPOT_CIRCUIT_BREAKER_THRESHOLD = env.int('HUBSPOT_CIRCUIT_BREAKER_THRESHOLD')
HUBSPOT_CIRCUIT_BREAKER_TIMEOUT = env.int('HUBSPOT_CIRCUIT_BREAKER_TIMEOUT')