# Generated by Django 5.2.4 on 2025-09-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('buyer_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue from buyer fees', max_digits=12)),
                ('seller_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Revenue from seller fees', max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total platform revenue (buyer + seller)', max_digits=12)),
                ('total_payments', models.PositiveIntegerField(default=0)),
                ('total_milestones_approved', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Revenue',
                'verbose_name_plural': 'Platform Revenues',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
