# Generated by Django 5.2.4 on 2025-09-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformrevenue',
            name='seller_revenue',
        ),
        migrations.AddField(
            model_name='platformrevenue',
            name='vat_collected',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue from vat collected', max_digits=12),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total platform revenue (buyer + vat)', max_digits=12),
        ),
    ]
