# Generated by Django 5.2.4 on 2025-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelApp', '0002_remove_platformrevenue_seller_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformrevenue',
            name='buyer_revenue',
        ),
        migrations.AddField(
            model_name='platformrevenue',
            name='seller_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue from seller fees', max_digits=12),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total platform revenue (seller + vat)', max_digits=12),
        ),
    ]
