# Generated by Django 5.1.11 on 2025-10-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='translation_key',
            field=models.CharField(blank=True, help_text='Translation key for i18n (e.g., notifications.project_created)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='translation_variables',
            field=models.JSONField(blank=True, help_text='Variables for translation interpolation', null=True),
        ),
    ]
