# Generated by Django 5.1.11 on 2025-10-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_translation_key_and_more'),
    ]

    operations = [
    ]
