# Generated by Django 5.2.4 on 2025-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('siret_number', models.CharField(blank=True, default='', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('seller', 'Seller'), ('professional-buyer', 'Professional Buyer')], max_length=20)),
                ('source', models.CharField(default='callback_form', max_length=50)),
                ('hubspot_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
