# Generated by Django 5.2.4 on 2025-10-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_callbackrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackrequest',
            name='hubspot_id',
        ),
    ]
