# Generated by Django 5.1.11 on 2025-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('professional-buyer', 'Professional Buyer'), ('buyer', 'Buyer')], max_length=20),
        ),
    ]
