# Generated by Django 5.2.4 on 2025-12-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_callbackrequest_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='role',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('professional-buyer', 'Professional Buyer'), ('buyer', 'Buyer')], default='', max_length=20),
        ),
    ]
