# Generated by Django 5.1.11 on 2025-09-15 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_id', models.CharField(db_index=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_contact_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HubSpot Contact Link',
                'verbose_name_plural': 'HubSpot Contact Links',
                'indexes': [models.Index(fields=['hubspot_id'], name='hubspot_hub_hubspot_fc3016_idx')],
            },
        ),
    ]
