# Generated by Django 5.2.4 on 2025-09-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_average_rating_user_rating_count'),
        ('hubspot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotCompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_id', models.CharField(db_index=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('business_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_company_link', to='accounts.businessdetail')),
            ],
            options={
                'verbose_name': 'HubSpot Company Link',
                'verbose_name_plural': 'HubSpot Company Links',
                'indexes': [models.Index(fields=['hubspot_id'], name='hubspot_hub_hubspot_37bfa5_idx')],
            },
        ),
    ]
