# Generated by Django 5.2.4 on 2025-09-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        ('hubspot', '0002_hubspotcompanylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotTicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_id', models.CharField(db_index=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_ticket_link', to='disputes.dispute')),
            ],
            options={
                'verbose_name': 'HubSpot Ticket Link',
                'verbose_name_plural': 'HubSpot Ticket Links',
                'indexes': [models.Index(fields=['hubspot_id'], name='hubspot_hub_hubspot_bef6be_idx')],
            },
        ),
    ]
