# Generated by Django 5.2.4 on 2025-09-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0003_hubspotticketlink'),
        ('projects', '0019_alter_milestone_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotMilestoneLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_id', models.CharField(db_index=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('milestone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_milestone_link', to='projects.milestone')),
            ],
            options={
                'verbose_name': 'HubSpot Milestone Link',
                'verbose_name_plural': 'HubSpot Milestone Links',
                'indexes': [models.Index(fields=['hubspot_id'], name='hubspot_hub_hubspot_1a8172_idx')],
            },
        ),
    ]
