# Generated by Django 5.1.11 on 2025-10-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hubspot', '0004_hubspotmilestonelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object being synced')),
                ('sync_type', models.CharField(choices=[('feedback', 'Feedback'), ('dispute', 'Dispute'), ('milestone', 'Milestone'), ('contact_message', 'Contact Message')], help_text='Type of sync operation', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('synced', 'Synced'), ('failed', 'Failed'), ('retry', 'Retry')], db_index=True, default='pending', help_text='Current status of the sync operation', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', help_text='Processing priority', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the sync was queued')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='When to process this sync (for delayed processing)', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the sync was completed', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, help_text='When to retry this sync', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Last error message if sync failed')),
                ('error_details', models.JSONField(blank=True, default=dict, help_text='Additional error details for debugging')),
                ('worker_id', models.CharField(blank=True, help_text='ID of the worker processing this item', max_length=100)),
                ('processing_started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('content_type', models.ForeignKey(help_text='The model type being synced', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'HubSpot Sync Queue Item',
                'verbose_name_plural': 'HubSpot Sync Queue Items',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='hubspot_hub_status_eca492_idx'), models.Index(fields=['sync_type', 'status'], name='hubspot_hub_sync_ty_f7abf7_idx'), models.Index(fields=['scheduled_at'], name='hubspot_hub_schedul_081a54_idx'), models.Index(fields=['next_retry_at'], name='hubspot_hub_next_re_2df9dc_idx'), models.Index(fields=['content_type', 'object_id'], name='hubspot_hub_content_8309ac_idx')],
                'unique_together': {('content_type', 'object_id', 'sync_type')},
            },
        ),
    ]
