# Generated by Django 5.2.4 on 2025-09-01 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, help_text='Stripe Connect account ID', max_length=255, null=True, unique=True)),
                ('account_status', models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('pending', 'Pending'), ('active', 'Active'), ('restricted', 'Restricted'), ('disconnected', 'Disconnected')], default='onboarding', help_text='Current status of the Stripe Connect account', max_length=20)),
                ('onboarding_complete', models.BooleanField(default=False, help_text='Whether Stripe Connect onboarding is complete')),
                ('account_data', models.JSONField(blank=True, default=dict, help_text='Additional Stripe account data and requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Account',
                'verbose_name_plural': 'Stripe Accounts',
            },
        ),
        migrations.CreateModel(
            name='StripeIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_session_id', models.CharField(blank=True, help_text='Stripe Identity verification session ID', max_length=999, null=True, unique=True)),
                ('identity_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('requires_input', 'Requires Input'), ('verified', 'Verified'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='not_started', help_text='Current status of identity verification', max_length=20)),
                ('identity_verified', models.BooleanField(default=False, help_text='Whether identity verification is complete')),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='Additional verification data and errors')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When identity verification was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Identity',
                'verbose_name_plural': 'Stripe Identities',
            },
        ),
    ]
