# Generated by Django 5.2.4 on 2025-09-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeidentity',
            name='identity_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('processing', 'Processing'), ('requires_input', 'Requires Input'), ('verified', 'Verified'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='not_started', help_text='Current status of identity verification', max_length=20),
        ),
    ]
