# Generated by Django 5.2.4 on 2025-09-03 20:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current available balance', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative earnings (all time)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total amount the user has spent as a buyer', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('held_in_escrow', models.DecimalField(decimal_places=2, default=0, help_text='Funds currently held for ongoing projects (escrow)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(help_text='Stripe transfer id (tr_...)', max_length=255, unique=True)),
                ('stripe_account_id', models.CharField(help_text='Destination Stripe Connect account id (acct_...)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_024e9b_idx'), models.Index(fields=['stripe_transfer_id'], name='payments_pa_stripe__bf5036_idx')],
            },
        ),
    ]
