# Generated by Django 5.2.4 on 2025-09-11 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_platformfeeconfig_balance_available_for_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformfeeconfig',
            name='buyer_fee_pct',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
