# Generated by Django 5.2.4 on 2025-09-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_platformfeeconfig_buyer_fee_pct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformFeeConfig',
        ),
    ]
