# Generated by Django 5.2.4 on 2025-09-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_delete_platformfeeconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_fee_amount',
        ),
    ]
