# Generated by Django 5.1.11 on 2025-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hubspot_payment_id',
            field=models.CharField(blank=True, help_text='HubSpot payment record ID', max_length=255, null=True),
        ),
    ]
