# Generated by Django 5.2.4 on 2025-07-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_about_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='skills',
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='service_area',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='type_of_activity',
            field=models.CharField(default='', max_length=255),
        ),
    ]
