# Generated by Django 5.2.4 on 2025-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_businessdetail_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
