# Generated by Django 5.2.4 on 2025-07-11 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('siret_number', models.CharField(max_length=50)),
                ('full_address', models.TextField()),
                ('type_of_activity', models.CharField(max_length=255)),
                ('service_area', models.CharField(max_length=255)),
                ('siret_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
