# Generated by Django 5.2.4 on 2025-07-11 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businessdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('iban', models.CharField(blank=True, max_length=34, unique=True)),
                ('bank_code', models.CharField(max_length=20)),
                ('branch_code', models.CharField(max_length=20)),
                ('rib_key', models.CharField(max_length=10, unique=True)),
                ('bic_swift', models.CharField(max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
