# Generated by Django 5.2.4 on 2025-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='company_contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='skills',
            field=models.TextField(blank=True, default='[]'),  # Store as JSON string
        ),
    ]
