# Generated by Django 5.2.4 on 2025-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_businessdetail_company_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
