# Generated by Django 5.2.4 on 2025-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='service_area_department_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
