# Generated by Django 5.2.4 on 2025-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_businessdetail_company_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
