# Generated by Django 5.2.4 on 2025-07-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_businessdetail_service_area_department_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='service_area_department_numbers',
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='department_numbers',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
