# Generated by Django 5.2.4 on 2025-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_businessdetail_service_area_department_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='selected_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='selected_subcategories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
