# Generated by Django 5.2.4 on 2025-07-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_businessdetail_company_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='company_phone_number',
        ),
    ]
