# Generated by Django 5.2.4 on 2025-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_businessdetail_selected_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='selected_service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
