# Generated by Django 5.2.4 on 2025-08-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_businessdetail_selected_service_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='service_area',
        ),
    ]
