# Generated by Django 5.2.4 on 2025-08-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_businessdetail_service_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='department_numbers',
        ),
    ]
