# Generated by Django 5.2.4 on 2025-08-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_businessdetail_department_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='skills',
        ),
    ]
