# Generated by Django 5.2.4 on 2025-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_businessdetail_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetail',
            old_name='company_contact_person',
            new_name='company_contact_person_first_name',
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='company_contact_person_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
