# Generated by Django 5.2.4 on 2025-08-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_company_contact_person_businessdetail_company_contact_person_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Whether this user has admin privileges assigned by super-admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('professional-buyer', 'Professional Buyer'), ('admin', 'Admin'), ('super-admin', 'Super Admin')], max_length=20),
        ),
    ]
