# Generated by Django 5.2.4 on 2025-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_average_rating_user_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('professional-buyer', 'Professional Buyer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='available_roles',
            field=models.JSONField(blank=True, default=list, help_text='System-managed field - users cannot edit this directly'),
        ),
        migrations.AddField(
            model_name='user',
            name='pro_buyer_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
