# Generated by Django 5.2.4 on 2025-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_average_rating_user_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('professional-buyer', 'Professional Buyer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_professional_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
