# Generated by Django 5.2.4 on 2025-10-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_active_role_user_is_professional_buyer_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE accounts_user "
                "ADD COLUMN IF NOT EXISTS is_seller boolean NOT NULL DEFAULT false;"
            ),
            reverse_sql=(
                "ALTER TABLE accounts_user "
                "DROP COLUMN IF EXISTS is_seller;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE accounts_user "
                "ADD COLUMN IF NOT EXISTS is_professional_buyer boolean NOT NULL DEFAULT false;"
            ),
            reverse_sql=(
                "ALTER TABLE accounts_user "
                "DROP COLUMN IF EXISTS is_professional_buyer;"
            ),
        ),
    ]
