# Generated by Django 5.2.4 on 2025-10-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_active_role_user_available_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.PositiveIntegerField(help_text='Original user ID before deletion', unique=True)),
                ('original_email', models.EmailField(help_text='Original email before deletion', max_length=254)),
                ('original_username', models.CharField(help_text='Original username before deletion', max_length=150)),
                ('original_role', models.CharField(help_text='Original user role', max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='When the account was deleted')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason provided by user', null=True)),
                ('deletion_initiated_by', models.CharField(choices=[('user', 'User Self-Initiated'), ('admin', 'Admin Deleted'), ('system', 'System Deleted'), ('compliance', 'Compliance Deleted')], default='user', help_text='Who initiated the deletion', max_length=20)),
                ('account_created_at', models.DateTimeField(help_text='When the original account was created')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Last login before deletion', null=True)),
                ('was_email_verified', models.BooleanField(default=False, help_text='Was email verified at deletion')),
                ('onboarding_complete', models.BooleanField(default=False, help_text='Was onboarding complete at deletion')),
                ('data_retention_until', models.DateTimeField(help_text='Data retention period end date')),
                ('gdpr_compliant', models.BooleanField(default=True, help_text='Deletion was GDPR compliant')),
            ],
            options={
                'verbose_name': 'Deleted User',
                'verbose_name_plural': 'Deleted Users',
                'db_table': 'deleted_users',
                'indexes': [models.Index(fields=['deleted_at'], name='deleted_use_deleted_5abed6_idx'), models.Index(fields=['original_user_id'], name='deleted_use_origina_95bfa8_idx'), models.Index(fields=['data_retention_until'], name='deleted_use_data_re_944cf1_idx')],
            },
        ),
    ]
