from django.urls import path
from .views import (
    create_stripe_payment,
    check_payment_status,
    list_billings,
    list_refunded_payments,
    balance_summary,
    transfer_to_stripe_account,
    get_transfer_info,
    list_transfers,
    generate_stripe_login_link,
    list_payout_holds,
    get_project_platform_fee,
    revenue_comparison,
    payment_refund,
    update_refund_balance,
)

urlpatterns = [
    path(
        "create-stripe-payment/<int:project_id>/",
        create_stripe_payment,
        name="create_stripe_payment",
    ),
    path(
        "check-payment-status/<int:project_id>/",
        check_payment_status,
        name="check_payment_status",
    ),
    path(
        "billings/",
        list_billings,
        name="list_billings",
    ),
    path(
        "refunds/",
        list_refunded_payments,
        name="list_refunded_payments",
    ),
    path(
        "balance/",
        balance_summary,
        name="balance_summary",
    ),
    path(
        "transfer-to-stripe/",
        transfer_to_stripe_account,
        name="transfer_to_stripe_account",
    ),
    path(
        "transfer-info/",
        get_transfer_info,
        name="get_transfer_info",
    ),
    path(
        "transfers/",
        list_transfers,
        name="list_transfers",
    ),
    path(
        "stripe-login-link/",
        generate_stripe_login_link,
        name="generate_stripe_login_link",
    ),
    path(
        "payout-holds/",
        list_payout_holds,
        name="list_payout_holds",
    ),
    path(
        "project-fees/<int:project_id>/",
        get_project_platform_fee,
        name="get_project_platform_fee",
    ),
    path(
        "revenue-comparison/",
        revenue_comparison,
        name="revenue_comparison",
    ),
    path(
        "payment-refund/<int:project_id>/",
        payment_refund,
        name="payment_refund",
    ),
    path(
        "update-refund-balance/<int:milestone_id>/",
        update_refund_balance,
        name="update_refund_balance",
    ),
]
