# Generated by Django 5.1.11 on 2025-12-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptioninvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='subscriptioninvoice',
            name='vat_rate',
        ),
    ]
