# Generated by Django 5.2.4 on 2025-07-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='invite_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
