# Generated by Django 5.2.4 on 2025-08-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('supporting_doc', models.FileField(blank=True, help_text='Supporting documentation for the milestone', null=True, upload_to='milestones/documents/')),
                ('completion_notice', models.TextField(blank=True, help_text='Notice sent when milestone is completed')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='Date when milestone was completed', null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved')], default='pending', max_length=20)),
                ('relative_payment', models.DecimalField(decimal_places=2, help_text='Payment amount for this milestone', max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
