# Generated by Django 5.2.4 on 2025-08-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='related_installment',
            field=models.OneToOneField(blank=True, help_text='The corresponding payment installment for this milestone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='projects.paymentinstallment'),
        ),
    ]
