# Generated by Django 5.2.4 on 2025-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved'), ('not_submitted', 'Not Submitted'), ('not_approved', 'Not Approved')], default='not_submitted', max_length=20),
        ),
    ]
