# Generated by Django 5.2.4 on 2025-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_milestone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='review_comment',
            field=models.TextField(blank=True, help_text='Comment from buyer when requesting review'),
        ),
    ]
