# Generated by Django 5.2.4 on 2025-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('real_project', 'Real Project'), ('quote_chat', 'Quote Chat')], default='real_project', help_text='Type of project - real project or quote chat', max_length=20),
        ),
    ]
