# Generated by Django 5.2.4 on 2025-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved'), ('not_submitted', 'Not Submitted')], default='not_submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_in_progress', 'Payment In Progress'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
