# Generated by Django 5.2.4 on 2025-09-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_milestone_status_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='refundable_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated refundable amount based on milestone adjustments and payments', max_digits=12),
        ),
    ]
