# Generated by Django 5.2.4 on 2025-09-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_refundable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invite_token_used',
            field=models.BooleanField(default=False, help_text='Whether the invite token has been used by the client'),
        ),
    ]
