# Generated by Django 5.2.4 on 2025-09-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_invite_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vat_rate',
            field=models.DecimalField(decimal_places=1, default=20.0, help_text='Applicable VAT rate percentage (e.g. 20.0 for 20%)', max_digits=4),
        ),
    ]
