# Generated by Django 5.2.4 on 2025-09-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Platform fee percentage applied to this project (e.g. 10.0 for 10%)', max_digits=5),
        ),
    ]
