# Generated by Django 5.2.4 on 2025-09-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_platform_fee_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('not_approved', 'Not Approved'), ('not_submitted', 'Not Submitted'), ('payment_withdrawal', 'Payment Withdrawal')], default='not_submitted', max_length=20),
        ),
    ]
