# Generated by Django 5.2.4 on 2025-10-07 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_milestone_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('client__isnull', True), models.Q(('user', models.F('client')), _negated=True), _connector='OR'), name='project_seller_not_equal_client'),
        ),
    ]
