# Generated by Django 5.1.11 on 2025-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_project_seller_not_equal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hubspot_payment_id',
            field=models.CharField(blank=True, help_text='HubSpot payment record ID for this project', max_length=255, null=True),
        ),
    ]
