# Generated by Django 5.2.4 on 2025-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_hubspot_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='platform_invoice_reference',
            field=models.CharField(blank=True, editable=False, help_text='Permanent platform invoice reference number (auto-generated, non-editable)', max_length=20, null=True, unique=True),
        ),
    ]
