# Generated by Django 5.1.15 on 2026-02-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_quote_platform_invoice_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=7.0, help_text='Platform fee percentage applied to this project (e.g. 7.0 for 7%)', max_digits=5),
        ),
    ]
