# Generated by Django 5.1.11 on 2025-12-07 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(db_index=True, help_text='Unique session identifier', unique=True)),
                ('title', models.CharField(blank=True, help_text='User-provided or auto-generated session title', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Session description or summary', null=True)),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages in this session')),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session was ended', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
                'db_table': 'chatbot_conversation_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotHistoryConversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for conversation thread')),
                ('user_query', models.TextField(help_text='Original user query')),
                ('response_text', models.TextField(blank=True, help_text='LLM-generated response (if applicable)', null=True)),
                ('query_embedding', models.JSONField(blank=True, help_text='Query embedding vector (768 dimensions for Google)', null=True)),
                ('retrieved_chunks', models.JSONField(blank=True, default=list, help_text='Top 5 retrieved chunks with metadata and scores')),
                ('context_summary', models.TextField(blank=True, help_text='Summary of conversation context for enrichment', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (provider, model, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When conversation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When conversation was last updated')),
                ('response_time_ms', models.IntegerField(default=0, help_text='Time taken to generate response in milliseconds')),
                ('embedding_time_ms', models.IntegerField(default=0, help_text='Time taken to generate embedding in milliseconds')),
                ('search_time_ms', models.IntegerField(default=0, help_text='Time taken to search Pinecone in milliseconds')),
                ('avg_chunk_score', models.FloatField(default=0.0, help_text='Average similarity score of retrieved chunks')),
                ('max_chunk_score', models.FloatField(default=0.0, help_text='Maximum similarity score of retrieved chunks')),
                ('user', models.ForeignKey(help_text='User who initiated the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='rag_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Conversation',
                'verbose_name_plural': 'Chatbot Conversations',
                'db_table': 'chatbot_history_conversation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'conversation_id'], name='chatbot_his_user_id_4398f7_idx'), models.Index(fields=['user', '-created_at'], name='chatbot_his_user_id_472002_idx'), models.Index(fields=['conversation_id', '-created_at'], name='chatbot_his_convers_43118b_idx'), models.Index(fields=['-created_at'], name='chatbot_his_created_c7a31a_idx')],
            },
        ),
    ]
