# Generated by Django 5.1.11 on 2025-12-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbothistoryconversation',
            name='anonymous_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymous user identifier (session/device ID)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatbothistoryconversation',
            name='is_authenticated',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether user was authenticated when creating conversation'),
        ),
        migrations.AlterField(
            model_name='chatbothistoryconversation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user (NULL for anonymous users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
